version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=turntable.proxy.rlwy.net
      - DB_PORT=45341
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=TzQyVysVNOEyngOMXFZOeOjsggEMKEnz
    depends_on:
      - nginx

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
